name: behavior_streamer
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/ciscofu/behavior_streamer

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
#dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
